/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.carlmontrobotics.webots.testproject;


import com.cyberbotics.webots.controller.Robot;

public class App {

    public Robot createRobot() {
        System.out.println("Creating Robot");
        Robot robot = new Robot();
        System.out.println("Robot created");
        Runtime.getRuntime().addShutdownHook(new Thread(robot::delete));
        int basicTimeStep = (int)Math.round(robot.getBasicTimeStep());
        robot.step(basicTimeStep);
        return robot;
    }

    public static void main(String[] args) {
        new App().createRobot();
    }
}
