/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.carlmontrobotics.gradle

import spock.lang.Specification
import org.apache.commons.io.FileUtils
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'org.carlmontrobotics.gradle.greeting' plugin.
 */
class WebotsPluginFunctionalTest extends Specification {
    def "warns about missing Webots installation"() { 
        given:
        def projectDir = new File("build/functionalTest")
        FileUtils.deleteDirectory(projectDir)
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "build.gradle") << """
            plugins {
                id('org.carlmontrobotics.gradle.webots')
            }

            task('printWebotsHome') {
                println webots.home
            }
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withEnvironment([WEBOTS_HOME: "build/functionalTest/missingwebotshome"])
        runner.withArguments("printWebotsHome")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("Can't find Webots installation")
    }
}
