/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.carlmontrobotics.webots.testproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCreatesARobot() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.createRobot(), "app should create a robot");
    }
}
