/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.carlmontrobotics.webots.testproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCreatesARobot() {
        System.out.println("LD_LIBRARY_PATH=" + System.getenv("LD_LIBRARY_PATH"));
        // assertEquals("expected", System.getenv("LD_LIBRARY_PATH"));
        App classUnderTest = null;
        classUnderTest = new App();
        assertNotNull(classUnderTest.createRobot(), "app should create a robot");
    }
}
